spring.application.name=task-management-api
spring.datasource.url=jdbc:mysql://localhost:3306/tasktb
spring.datasource.username=DB_USERNAME
spring.datasource.password=DB_PASSWORD
server.port=8082
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
